from . import register
from . import search
from . import help
from . import recent
from . import top
from . import stats
from . import beatmaps
from . import leaderboard
from . import admin
from . import changepfp